NetBazaar/Controllers/PostingsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using MongoDB.Driver;
using NetBazaar.BusinessLogic;
using NetBazaar.BusinessLogic.Interfaces;
using NetBazaar.Dalc.Dtos;
using NetBazaar.Dalc.Interfaces;
using NetBazaar.ViewModels.ActionResultViewModels;
using NetBazaar.ViewModels.CategoryViewModels;
using NetBazaar.ViewModels.PostingViewModels;

namespace NetBazaar.Controllers
{
    [Authorize(Roles = "Administrator,Member")]
    public class PostingsController : Controller
    {
        private readonly ICategoriesStore _categoriesStore;
        private readonly IImageHostingService _imageHostingService;
        private readonly NetBazaarDatabase _netBazaarDatabase;
        private readonly IPostingsStore _postingsStore;
        private IMongoDatabase _netBazaarMongoDb;

        public PostingsController(IPostingsStore postingsStore, ICategoriesStore categoriesStore,
            IImageHostingService imageHostingService, NetBazaarDatabase netBazaarDatabase,
            IMongoDatabase netBazaarMongoDb)
        {
            _postingsStore = postingsStore;
            _categoriesStore = categoriesStore;
            _imageHostingService = imageHostingService;
            _netBazaarDatabase = netBazaarDatabase;
            _netBazaarMongoDb = netBazaarMongoDb;
        }

        // GET: Postings
        public async Task<ActionResult> Index()
        {
            return View("Categories");
        }


        [HttpPost]
        [ValidateJsonAntiForgeryToken]
        public async Task<ActionResult> GetCategories()
        {
            var categories = await _categoriesStore.GetCategoriesAsync();
            var categoriesList = new List<CategoryViewModel>();

            foreach (var category in categories)
            {
                categoriesList.Add(category);
            }


            return new JsonNetResult(new GetActionResultViewModel<List<CategoryViewModel>>
            {
                IsSuccessful = true,
                Data = categoriesList
            });
        }

        public async Task<ActionResult> CategoryPostings(long categoryId)
        {
            ViewBag.CategoryId = categoryId;
            return View("CategoryPostings");
        }

        public async Task<ActionResult> GetCategoryPostings(long categoryId)
        {
            var category = await _categoriesStore.GetCategoryByIdAsync(categoryId);
            var postingsFromCategory = await _postingsStore.GetPostingsFromCategory(categoryId, 10000, 1);

            return new JsonNetResult(new GetActionResultViewModel<PostingsWithCategoryViewModel>
            {
                IsSuccessful = true,
                Data = new PostingsWithCategoryViewModel {Category = category, Postings = postingsFromCategory}
            });
        }

        // GET: Postings/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var posting = await _netBazaarDatabase.Postings.FindAsync(id);
            if (posting == null)
            {
                return HttpNotFound();
            }
            return View(posting);
        }

        // GET: Postings/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(_netBazaarDatabase.AspNetUsers, "Id", "Hometown");
            ViewBag.CategoryId = new SelectList(_netBazaarDatabase.Categories, "Id", "Name");
            return View();
        }

        // POST: Postings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,UserId,CategoryId,Type,Title,Description,PostingDate,ExpirationDate")] Posting posting)
        {
            if (ModelState.IsValid)
            {
                _netBazaarDatabase.Postings.Add(posting);
                await _netBazaarDatabase.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(_netBazaarDatabase.AspNetUsers, "Id", "Hometown", posting.UserId);
            ViewBag.CategoryId = new SelectList(_netBazaarDatabase.Categories, "Id", "Name", posting.CategoryId);
            return View(posting);
        }

        // GET: Postings/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var posting = await _netBazaarDatabase.Postings.FindAsync(id);
            if (posting == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(_netBazaarDatabase.AspNetUsers, "Id", "Hometown", posting.UserId);
            ViewBag.CategoryId = new SelectList(_netBazaarDatabase.Categories, "Id", "Name", posting.CategoryId);
            return View(posting);
        }

        // POST: Postings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(Include = "Id,UserId,CategoryId,Type,Title,Description,PostingDate,ExpirationDate")] Posting posting)
        {
            if (ModelState.IsValid)
            {
                _netBazaarDatabase.Entry(posting).State = EntityState.Modified;
                await _netBazaarDatabase.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(_netBazaarDatabase.AspNetUsers, "Id", "Hometown", posting.UserId);
            ViewBag.CategoryId = new SelectList(_netBazaarDatabase.Categories, "Id", "Name", posting.CategoryId);
            return View(posting);
        }

        // GET: Postings/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var posting = await _netBazaarDatabase.Postings.FindAsync(id);
            if (posting == null)
            {
                return HttpNotFound();
            }
            return View(posting);
        }

        // POST: Postings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            var posting = await _netBazaarDatabase.Postings.FindAsync(id);
            _netBazaarDatabase.Postings.Remove(posting);
            await _netBazaarDatabase.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _netBazaarDatabase.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NetBazaar/Views/Postings/Categories.cshtml
@{
    ViewBag.Title = "Categories";
}

<h2>Postings</h2>

<div class="form-horizontal" data-bind="foreach: categories">

    <div class="col-md-6" data-bind="click: $root.navigateToCategory">
        <div style="margin-left: 10px" class="panel panel-default clickable">
            <img data-bind="attr: { src : url }" width="64" height="64"/>
            <h3 data-bind="text: name"></h3>
        </div>
    </div>

</div>

@section scripts
{
    <script>
        var Category = function(id, name, url) {
            this.id = id;
            this.name = ko.observable(name);
            this.url = url;
        };

        var listCategoriesModel = {
            categories: ko.observableArray(),
            navigateToCategory: function(category) {
                window.location.href = "@Url.RouteUrl("ShowCategoryPostings", new {id = "{0}"})".replace("{0}",
                    category.id);
            }
        };

        ko.applyBindings(listCategoriesModel);


        $.ajax("@Url.Action("GetCategories", "Postings")",
            {
                type: 'POST',
                traditional: true,
                headers: { __RequestVerificationToken: $('input[name=__RequestVerificationToken]').val() }
            })
            .done(function(response) {
                for (var i = 0; i < response.data.length; i++) {
                    listCategoriesModel.categories.push(new Category(response.data[i].id,
                        response.data[i].name,
                        response.data[i].image.url || "#"));
                }
            });

    </script>
}

NetBazaar/Views/Postings/CategoryPostings.cshtml
<h2 data-bind="text: categoryTitle">Postings</h2>
<hr/>
<h3 data-bind="text: categoryDescription">Postings</h3>

<p>
    <a href="@Url.RouteUrl("CreateCategoryPosting", new { id = ViewBag.CategoryId })" class="btn btn-default">Create CategoryPostings</a>
</p>


<div class="form-horizontal" data-bind="foreach: postings">

    <div class="col-md-6" data-bind="click: $root.navigateToPosting">
        <div style="margin-left: 10px" class="panel panel-default clickable">
            <h3 data-bind="text: name"></h3>
        </div>
    </div>

</div>

@section scripts
{
    <script>
        var Posting = function(id, name) {
            this.id = id;
            this.name = ko.observable(name);
        };

        var listCategoriesModel = {
            postings: ko.observableArray(),
            navigateToPosting: function() {
                alert("click");
            }
        };

        ko.applyBindings(listCategoriesModel);


        $.ajax("@Url.Action("GetCategoryPostings", "Postings")",
            {
                type: 'POST',
                traditional: true,
                headers: { __RequestVerificationToken: $('input[name=__RequestVerificationToken]').val() }
            })
            .done(function(response) {
                for (var i = 0; i < response.data.length; i++) {
                    listCategoriesModel.categories.push(new Posting(response.data[i].id,
                        response.data[i].name));
                }
            });

    </script>
}

NetBazaar/Views/Postings/Create.cshtml
@model NetBazaar.Dalc.Dtos.Posting

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Posting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NetBazaar/Views/Postings/Delete.cshtml
@model NetBazaar.Dalc.Dtos.Posting

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Posting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Hometown)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Hometown)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NetBazaar/Views/Postings/Details.cshtml
@model NetBazaar.Dalc.Dtos.Posting

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Posting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Hometown)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Hometown)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NetBazaar/Views/Postings/Edit.cshtml
@model NetBazaar.Dalc.Dtos.Posting

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Posting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}